name: Build LaTeX documents

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile paper
        uses: xu-cheng/latex-action@v2
        with:
          root_file: 000_rust.tex
      - name: Check pdf files
        run: |
          file 000_rust.pdf | grep -q ' PDF '
      - name: Rename pdf files
        run: |
          mv 000_rust.pdf rust.pdf
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: rust
          path: |
            rust.pdf
        if: always()
